### ISSUE TITLE
RSS 项目太少了

### ISSUE THREAD

**Issue by YDX-2147483647** [YDX-2147483647/bulletin-issues-transferred#29]
https://github.com/YDX-2147483647/bulletin-issues-transferred/blob/661d9527d09eaa898c872ef1b0c34a10296a5657/src/plugin/rss/index.ts#LL10C1-L10C90

现在有 34 个通知来源，RSS 默认条数却才 30……

**Comment by YDX-2147483647** [comment]
@CZLeader 要不加到 100？

**Comment by CZLeader** [comment]
可以加吗，可以加就加
&nbsp;


Mr&nbsp;Liu
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月21日(星期天) 晚上11:25
收件人: ***@***.***&gt;; 
抄送: "Mr ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YDX-2147483647/bulletin-issues-transferred] RSS 项目太少了 (Issue #29)





 
@CZLeader 要不加到 100？

**Comment by YDX-2147483647** [comment]
改`config/config.yml`的`rss.max_items`就行。

已改。

```powershell
> https haobit.top/dev/feed.rss --pretty all | rg '<item>' | measure
Count: 100
```
